/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/backtests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List/inspect backtests and queue new runs.
         *
         *     Creating a backtest executes the run synchronously and returns the finished
         *     record. If the engine fails, the record is returned with ``status=failed``
         *     and an ``error_message`` rather than surfacing a 500.
         */
        get: operations["backtests_list"];
        put?: never;
        /**
         * @description List/inspect backtests and queue new runs.
         *
         *     Creating a backtest executes the run synchronously and returns the finished
         *     record. If the engine fails, the record is returned with ``status=failed``
         *     and an ``error_message`` rather than surfacing a 500.
         */
        post: operations["backtests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List/inspect backtests and queue new runs.
         *
         *     Creating a backtest executes the run synchronously and returns the finished
         *     record. If the engine fails, the record is returned with ``status=failed``
         *     and an ``error_message`` rather than surfacing a 500.
         */
        get: operations["backtests_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/{id}/trades/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return the trade log produced by this backtest. */
        get: operations["backtests_trades_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for strategy definitions. */
        get: operations["strategies_list"];
        put?: never;
        /** @description CRUD for strategy definitions. */
        post: operations["strategies_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CRUD for strategy definitions. */
        get: operations["strategies_retrieve"];
        /** @description CRUD for strategy definitions. */
        put: operations["strategies_update"];
        post?: never;
        /** @description CRUD for strategy definitions. */
        delete: operations["strategies_destroy"];
        options?: never;
        head?: never;
        /** @description CRUD for strategy definitions. */
        patch: operations["strategies_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Read representation of a backtest run, including aggregate metrics. */
        Backtest: {
            readonly id: number;
            readonly strategy: number;
            readonly strategy_name: string;
            /** @description Instrument ticker, e.g. BTCUSDT */
            readonly symbol: string;
            /** @description Candle timeframe, e.g. 1m, 1h, 1d */
            readonly timeframe: string;
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string;
            /** Format: decimal */
            readonly initial_capital: string;
            /**
             * Format: double
             * @description Taker fee per side, fraction (0.0004 = 0.04%)
             */
            readonly commission_pct: number;
            /**
             * Format: double
             * @description Adverse fill per side, basis points
             */
            readonly slippage_bps: number;
            /**
             * Format: double
             * @description Half-spread crossed per side, basis points
             */
            readonly spread_bps: number;
            /**
             * Format: double
             * @description Funding per interval, fraction (longs pay if > 0)
             */
            readonly funding_rate: number;
            /**
             * Format: double
             * @description Hours between funding charges
             */
            readonly funding_interval_hours: number;
            readonly status: components["schemas"]["BacktestStatusEnum"];
            /** Format: decimal */
            readonly final_equity: string | null;
            /** Format: double */
            readonly total_return_pct: number | null;
            /** Format: double */
            readonly max_drawdown_pct: number | null;
            /** Format: double */
            readonly sharpe_ratio: number | null;
            /** Format: double */
            readonly win_rate_pct: number | null;
            readonly error_message: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly completed_at: string | null;
        };
        /**
         * @description Write payload to queue a backtest run.
         *
         *     Only the run configuration is accepted; status, metrics and trades are
         *     produced by the engine. Cost fields are optional and fall back to the
         *     model's realistic defaults (CLAUDE.md §7) — results are never cost-free.
         */
        BacktestCreate: {
            strategy: number;
            /** @description Instrument ticker, e.g. BTCUSDT */
            symbol: string;
            /** @description Candle timeframe, e.g. 1m, 1h, 1d */
            timeframe?: string;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** Format: decimal */
            initial_capital?: string;
            /**
             * Format: double
             * @description Taker fee per side, fraction (0.0004 = 0.04%)
             */
            commission_pct?: number;
            /**
             * Format: double
             * @description Adverse fill per side, basis points
             */
            slippage_bps?: number;
            /**
             * Format: double
             * @description Half-spread crossed per side, basis points
             */
            spread_bps?: number;
            /**
             * Format: double
             * @description Funding per interval, fraction (longs pay if > 0)
             */
            funding_rate?: number;
            /**
             * Format: double
             * @description Hours between funding charges
             */
            funding_interval_hours?: number;
        };
        /**
         * @description Backtest read representation including the full equity curve.
         *
         *     Used for retrieve/create responses; the list endpoint uses the lighter
         *     :class:`BacktestSerializer` to avoid shipping the curve for every row.
         */
        BacktestDetail: {
            readonly id: number;
            readonly strategy: number;
            readonly strategy_name: string;
            /** @description Instrument ticker, e.g. BTCUSDT */
            readonly symbol: string;
            /** @description Candle timeframe, e.g. 1m, 1h, 1d */
            readonly timeframe: string;
            /** Format: date */
            readonly start_date: string;
            /** Format: date */
            readonly end_date: string;
            /** Format: decimal */
            readonly initial_capital: string;
            /**
             * Format: double
             * @description Taker fee per side, fraction (0.0004 = 0.04%)
             */
            readonly commission_pct: number;
            /**
             * Format: double
             * @description Adverse fill per side, basis points
             */
            readonly slippage_bps: number;
            /**
             * Format: double
             * @description Half-spread crossed per side, basis points
             */
            readonly spread_bps: number;
            /**
             * Format: double
             * @description Funding per interval, fraction (longs pay if > 0)
             */
            readonly funding_rate: number;
            /**
             * Format: double
             * @description Hours between funding charges
             */
            readonly funding_interval_hours: number;
            readonly status: components["schemas"]["BacktestStatusEnum"];
            /** Format: decimal */
            readonly final_equity: string | null;
            /** Format: double */
            readonly total_return_pct: number | null;
            /** Format: double */
            readonly max_drawdown_pct: number | null;
            /** Format: double */
            readonly sharpe_ratio: number | null;
            /** Format: double */
            readonly win_rate_pct: number | null;
            readonly error_message: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly completed_at: string | null;
            readonly equity_curve: components["schemas"]["EquityPoint"][];
        };
        /**
         * @description * `pending` - Pending
         *     * `running` - Running
         *     * `completed` - Completed
         *     * `failed` - Failed
         * @enum {string}
         */
        BacktestStatusEnum: "pending" | "running" | "completed" | "failed";
        /** @description One sample of portfolio value on the equity curve. */
        EquityPoint: {
            /**
             * Format: date-time
             * @description Sample timestamp (ISO-8601).
             */
            t: string;
            /**
             * Format: double
             * @description Portfolio value at this time.
             */
            equity: number;
        };
        /**
         * @description * `sma_crossover` - SMA Crossover
         *     * `rsi` - RSI
         * @enum {string}
         */
        KindEnum: "sma_crossover" | "rsi";
        PaginatedBacktestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Backtest"][];
        };
        PaginatedStrategyList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Strategy"][];
        };
        PaginatedTradeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Trade"][];
        };
        /**
         * @description A strategy definition.
         *
         *     ``parameters`` is a free-form JSON object. It carries the engine-facing
         *     parameters (e.g. ``fast``/``slow``) at the top level plus a reserved
         *     ``_meta`` envelope (schema version + logic graph) written by the frontend.
         *     The backtest engine reads only the keys it knows and ignores the rest.
         */
        PatchedStrategy: {
            readonly id?: number;
            name?: string;
            description?: string;
            kind?: components["schemas"]["KindEnum"];
            parameters?: unknown;
            status?: components["schemas"]["StrategyStatusEnum"];
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `long` - Long
         *     * `short` - Short
         * @enum {string}
         */
        SideEnum: "long" | "short";
        /**
         * @description A strategy definition.
         *
         *     ``parameters`` is a free-form JSON object. It carries the engine-facing
         *     parameters (e.g. ``fast``/``slow``) at the top level plus a reserved
         *     ``_meta`` envelope (schema version + logic graph) written by the frontend.
         *     The backtest engine reads only the keys it knows and ignores the rest.
         */
        Strategy: {
            readonly id: number;
            name: string;
            description?: string;
            kind?: components["schemas"]["KindEnum"];
            parameters?: unknown;
            status?: components["schemas"]["StrategyStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `active` - Active
         *     * `archived` - Archived
         * @enum {string}
         */
        StrategyStatusEnum: "draft" | "active" | "archived";
        /** @description An individual simulated trade. PnL fields are net of trading costs. */
        Trade: {
            readonly id: number;
            readonly backtest: number;
            readonly side: components["schemas"]["SideEnum"];
            /** Format: decimal */
            readonly quantity: string;
            /** Format: date-time */
            readonly entry_time: string;
            /** Format: decimal */
            readonly entry_price: string;
            /** Format: date-time */
            readonly exit_time: string | null;
            /** Format: decimal */
            readonly exit_price: string | null;
            /** Format: decimal */
            readonly gross_pnl: string | null;
            /** Format: decimal */
            readonly commission: string;
            /** Format: decimal */
            readonly funding: string;
            /** Format: decimal */
            readonly pnl: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    backtests_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Filter runs by strategy id. */
                strategy?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedBacktestList"];
                };
            };
        };
    };
    backtests_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["BacktestCreate"];
                "multipart/form-data": components["schemas"]["BacktestCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetail"];
                };
            };
        };
    };
    backtests_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this backtest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestDetail"];
                };
            };
        };
    };
    backtests_trades_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this backtest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTradeList"];
                };
            };
        };
    };
    strategies_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStrategyList"];
                };
            };
        };
    };
    strategies_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Strategy"];
                "application/x-www-form-urlencoded": components["schemas"]["Strategy"];
                "multipart/form-data": components["schemas"]["Strategy"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
        };
    };
    strategies_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this strategy. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
        };
    };
    strategies_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this strategy. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Strategy"];
                "application/x-www-form-urlencoded": components["schemas"]["Strategy"];
                "multipart/form-data": components["schemas"]["Strategy"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
        };
    };
    strategies_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this strategy. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    strategies_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this strategy. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedStrategy"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedStrategy"];
                "multipart/form-data": components["schemas"]["PatchedStrategy"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
        };
    };
}
